/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MyService_H
#define MyService_H

#include <TProcessor.h>
#include "mp2_types.h"

namespace mp2 {

class MyServiceIf {
 public:
  virtual ~MyServiceIf() {}
  virtual void an_rpc_func(MyObject& _return, const MyObject& in_object, const int32_t another_arg, const std::vector<std::string> & arg3) = 0;
  virtual void another_rpc_func(std::vector<MyObject> & _return) = 0;
};

class MyServiceIfFactory {
 public:
  typedef MyServiceIf Handler;

  virtual ~MyServiceIfFactory() {}

  virtual MyServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MyServiceIf* /* handler */) = 0;
};

class MyServiceIfSingletonFactory : virtual public MyServiceIfFactory {
 public:
  MyServiceIfSingletonFactory(const boost::shared_ptr<MyServiceIf>& iface) : iface_(iface) {}
  virtual ~MyServiceIfSingletonFactory() {}

  virtual MyServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MyServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MyServiceIf> iface_;
};

class MyServiceNull : virtual public MyServiceIf {
 public:
  virtual ~MyServiceNull() {}
  void an_rpc_func(MyObject& /* _return */, const MyObject& /* in_object */, const int32_t /* another_arg */, const std::vector<std::string> & /* arg3 */) {
    return;
  }
  void another_rpc_func(std::vector<MyObject> & /* _return */) {
    return;
  }
};

typedef struct _MyService_an_rpc_func_args__isset {
  _MyService_an_rpc_func_args__isset() : in_object(false), another_arg(false), arg3(false) {}
  bool in_object;
  bool another_arg;
  bool arg3;
} _MyService_an_rpc_func_args__isset;

class MyService_an_rpc_func_args {
 public:

  MyService_an_rpc_func_args() : another_arg(0) {
  }

  virtual ~MyService_an_rpc_func_args() throw() {}

  MyObject in_object;
  int32_t another_arg;
  std::vector<std::string>  arg3;

  _MyService_an_rpc_func_args__isset __isset;

  void __set_in_object(const MyObject& val) {
    in_object = val;
  }

  void __set_another_arg(const int32_t val) {
    another_arg = val;
  }

  void __set_arg3(const std::vector<std::string> & val) {
    arg3 = val;
  }

  bool operator == (const MyService_an_rpc_func_args & rhs) const
  {
    if (!(in_object == rhs.in_object))
      return false;
    if (!(another_arg == rhs.another_arg))
      return false;
    if (!(arg3 == rhs.arg3))
      return false;
    return true;
  }
  bool operator != (const MyService_an_rpc_func_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyService_an_rpc_func_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyService_an_rpc_func_pargs {
 public:


  virtual ~MyService_an_rpc_func_pargs() throw() {}

  const MyObject* in_object;
  const int32_t* another_arg;
  const std::vector<std::string> * arg3;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyService_an_rpc_func_result__isset {
  _MyService_an_rpc_func_result__isset() : success(false) {}
  bool success;
} _MyService_an_rpc_func_result__isset;

class MyService_an_rpc_func_result {
 public:

  MyService_an_rpc_func_result() {
  }

  virtual ~MyService_an_rpc_func_result() throw() {}

  MyObject success;

  _MyService_an_rpc_func_result__isset __isset;

  void __set_success(const MyObject& val) {
    success = val;
  }

  bool operator == (const MyService_an_rpc_func_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MyService_an_rpc_func_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyService_an_rpc_func_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyService_an_rpc_func_presult__isset {
  _MyService_an_rpc_func_presult__isset() : success(false) {}
  bool success;
} _MyService_an_rpc_func_presult__isset;

class MyService_an_rpc_func_presult {
 public:


  virtual ~MyService_an_rpc_func_presult() throw() {}

  MyObject* success;

  _MyService_an_rpc_func_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class MyService_another_rpc_func_args {
 public:

  MyService_another_rpc_func_args() {
  }

  virtual ~MyService_another_rpc_func_args() throw() {}


  bool operator == (const MyService_another_rpc_func_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MyService_another_rpc_func_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyService_another_rpc_func_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyService_another_rpc_func_pargs {
 public:


  virtual ~MyService_another_rpc_func_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyService_another_rpc_func_result__isset {
  _MyService_another_rpc_func_result__isset() : success(false) {}
  bool success;
} _MyService_another_rpc_func_result__isset;

class MyService_another_rpc_func_result {
 public:

  MyService_another_rpc_func_result() {
  }

  virtual ~MyService_another_rpc_func_result() throw() {}

  std::vector<MyObject>  success;

  _MyService_another_rpc_func_result__isset __isset;

  void __set_success(const std::vector<MyObject> & val) {
    success = val;
  }

  bool operator == (const MyService_another_rpc_func_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MyService_another_rpc_func_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyService_another_rpc_func_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyService_another_rpc_func_presult__isset {
  _MyService_another_rpc_func_presult__isset() : success(false) {}
  bool success;
} _MyService_another_rpc_func_presult__isset;

class MyService_another_rpc_func_presult {
 public:


  virtual ~MyService_another_rpc_func_presult() throw() {}

  std::vector<MyObject> * success;

  _MyService_another_rpc_func_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MyServiceClient : virtual public MyServiceIf {
 public:
  MyServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  MyServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void an_rpc_func(MyObject& _return, const MyObject& in_object, const int32_t another_arg, const std::vector<std::string> & arg3);
  void send_an_rpc_func(const MyObject& in_object, const int32_t another_arg, const std::vector<std::string> & arg3);
  void recv_an_rpc_func(MyObject& _return);
  void another_rpc_func(std::vector<MyObject> & _return);
  void send_another_rpc_func();
  void recv_another_rpc_func(std::vector<MyObject> & _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MyServiceProcessor : public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<MyServiceIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (MyServiceProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_an_rpc_func(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_another_rpc_func(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MyServiceProcessor(boost::shared_ptr<MyServiceIf> iface) :
    iface_(iface) {
    processMap_["an_rpc_func"] = &MyServiceProcessor::process_an_rpc_func;
    processMap_["another_rpc_func"] = &MyServiceProcessor::process_another_rpc_func;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~MyServiceProcessor() {}
};

class MyServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MyServiceProcessorFactory(const ::boost::shared_ptr< MyServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MyServiceIfFactory > handlerFactory_;
};

class MyServiceMultiface : virtual public MyServiceIf {
 public:
  MyServiceMultiface(std::vector<boost::shared_ptr<MyServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MyServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MyServiceIf> > ifaces_;
  MyServiceMultiface() {}
  void add(boost::shared_ptr<MyServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void an_rpc_func(MyObject& _return, const MyObject& in_object, const int32_t another_arg, const std::vector<std::string> & arg3) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->an_rpc_func(_return, in_object, another_arg, arg3);
        return;
      } else {
        ifaces_[i]->an_rpc_func(_return, in_object, another_arg, arg3);
      }
    }
  }

  void another_rpc_func(std::vector<MyObject> & _return) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->another_rpc_func(_return);
        return;
      } else {
        ifaces_[i]->another_rpc_func(_return);
      }
    }
  }

};

} // namespace

#endif
